### ISSUE TITLE
Would be better to update current value rather than explicitely set the value

### ISSUE THREAD

**Issue by michaelsudnik** [DevExpress-Examples/how-to-implement-the-drag-and-drop-functionality-for-the-token-editor-t558732#1]
https://github.com/DevExpress-Examples/how-to-implement-the-drag-and-drop-functionality-for-the-token-editor-t558732/blob/c0828bebf991d042de0cfd0714f013869eb67c23/CS/T558732/DragDropBehavior.cs#L63

Use this instead
`ownerEdit.SetCurrentValue(LookUpEditBase.EditValueProperty, result)`

**Comment by Andre644** [comment]
Thank you. I've made the corresponding amendments.
